import { Bar } from './bars';
import { DrinkCategory } from './drinkCategory';

export const BARS: Bar[] = [
    {
        id: 1, name: 'Gefängnisbar', drinks: [
            { name: 'Mineral (0.5l)', category: DrinkCategory.SOFT_DRINKS, interval: 1 },
            { name: 'Coca Cola ( 0.5l)', category: DrinkCategory.SOFT_DRINKS, interval: 1 },
            { name: 'Ice Tea Lemon (0.5l)', category: DrinkCategory.SOFT_DRINKS, interval: 1 },
            { name: 'Citro (1.5l)', category: DrinkCategory.SOFT_DRINKS, interval: 1 },
            { name: 'Trojka Energy (0.25l)', category: DrinkCategory.SOFT_DRINKS, interval: 1 },
            { name: 'Queen`s Cola (1.5l)', category: DrinkCategory.SOFT_DRINKS, interval: 1 },
            { name: 'Bitter Lemon (1.0l)', category: DrinkCategory.SOFT_DRINKS, interval: 1 },
            { name: 'FS Original (0.33l)', category: DrinkCategory.BEER_WINE, interval: 1 },
            { name: 'EVE Grapefruit Cosmopolitan', category: DrinkCategory.BEER_WINE, interval: 1 },
            { name: 'Braufrisch (0,33l)', category: DrinkCategory.BEER_WINE, interval: 1 },
            { name: 'Somersby', category: DrinkCategory.BEER_WINE, interval: 1 },
            { name: 'Trojka Vodka White', category: DrinkCategory.SPIRITS, interval: 1 },
            { name: 'Trojka Vodka Red', category: DrinkCategory.SPIRITS, interval: 1 },
            { name: 'Trojka Vodka Green', category: DrinkCategory.SPIRITS, interval: 1 },
            { name: 'Bacardi Superior', category: DrinkCategory.SPIRITS, interval: 1 },
            { name: 'Captain Morgan', category: DrinkCategory.SPIRITS, interval: 1 },
            { name: 'Smirnoff Ice', category: DrinkCategory.SPIRITS, interval: 1 },
            { name: 'Berliner Luft ', category: DrinkCategory.SPIRITS, interval: 1 },
            { name: 'Jägermeister (0,02l)', category: DrinkCategory.SPIRITS, interval: 1 },
            { name: 'Jägermeister (0,7l)', category: DrinkCategory.SPIRITS, interval: 1 },
            { name: 'Trojka Flamingo', category: DrinkCategory.SPIRITS, interval: 1 },
            { name: 'Eiswürfel (Kübel)', category: DrinkCategory.MATERIAL, interval: 1 },
            { name: 'Longdrinkbecher', category: DrinkCategory.MATERIAL, interval: 2 },
            { name: 'Shotbecher', category: DrinkCategory.MATERIAL, interval: 2 },
            { name: 'Röhrli kurz', category: DrinkCategory.MATERIAL, interval: 2 }
        ]
    },
    {
        id: 2, name: 'Helvetia Bar', drinks: [
            { name: 'Mineral (0.5l)', category: DrinkCategory.SOFT_DRINKS, interval: 1 },
            { name: 'Coca Cola ( 0.5l)', category: DrinkCategory.SOFT_DRINKS, interval: 1 },
            { name: 'Ice Tea Lemon (0.5l)', category: DrinkCategory.SOFT_DRINKS, interval: 1 },
            { name: 'Citro (1.5l)', category: DrinkCategory.SOFT_DRINKS, interval: 1 },
            { name: 'Trojka Energy (0.25l)', category: DrinkCategory.SOFT_DRINKS, interval: 1 },
            { name: 'Queen`s Cola (1.5l)', category: DrinkCategory.SOFT_DRINKS, interval: 1 },
            { name: 'Schweppes Indian Tonic', category: DrinkCategory.SOFT_DRINKS, interval: 1 },
            { name: 'Mineral (1.5l)', category: DrinkCategory.SOFT_DRINKS, interval: 1 },
            { name: 'FS Original (0.33l)', category: DrinkCategory.BEER_WINE, interval: 1 },
            { name: 'EVE Grapefruit Cosmopolitan', category: DrinkCategory.BEER_WINE, interval: 1 },
            { name: 'Braufrisch (0,33l)', category: DrinkCategory.BEER_WINE, interval: 1 },
            { name: 'Somersby', category: DrinkCategory.BEER_WINE, interval: 1 },
            { name: 'Prosecco Spumante', category: DrinkCategory.BEER_WINE, interval: 1 },
            { name: 'Trojka Vodka White', category: DrinkCategory.SPIRITS, interval: 1 },
            { name: 'Trojka Vodka Red', category: DrinkCategory.SPIRITS, interval: 1 },
            { name: 'Trojka Vodka Green', category: DrinkCategory.SPIRITS, interval: 1 },
            { name: 'Bacardi Superior', category: DrinkCategory.SPIRITS, interval: 1 },
            { name: 'Willi Sauer', category: DrinkCategory.SPIRITS, interval: 1 },
            { name: 'Aperol', category: DrinkCategory.SPIRITS, interval: 1 },
            { name: 'Smirnoff Ice', category: DrinkCategory.BEER_WINE, interval: 1 },
            { name: 'Gin Escape 7', category: DrinkCategory.SPIRITS, interval: 1 },
            { name: 'Feigling Coco Biscuit', category: DrinkCategory.SPIRITS, interval: 1 },
            { name: 'Eiswürfel (Kübel)', category: DrinkCategory.MATERIAL, interval: 1 },
            { name: 'Longdrinkbecher', category: DrinkCategory.MATERIAL, interval: 2 },
            { name: 'Shotbecher', category: DrinkCategory.MATERIAL, interval: 2 },
            { name: 'Röhrli kurz', category: DrinkCategory.MATERIAL, interval: 2 },
            { name: 'Cüplibecher ', category: DrinkCategory.MATERIAL, interval: 2 },
            { name: 'Orangen', category: DrinkCategory.MATERIAL, interval: 2 }
        ]
    },
    {
        id: 3, name: 'Black & White Bar', drinks: [
            { name: 'Mineral (0.5l)', category: DrinkCategory.SOFT_DRINKS, interval: 1 },
            { name: 'Coca Cola ( 0.5l)', category: DrinkCategory.SOFT_DRINKS, interval: 1 },
            { name: 'Ice Tea Lemon (0.5l)', category: DrinkCategory.SOFT_DRINKS, interval: 1 },
            { name: 'Citro (1.5l)', category: DrinkCategory.SOFT_DRINKS, interval: 1 },
            { name: 'Trojka Energy (0.25l)', category: DrinkCategory.SOFT_DRINKS, interval: 1 },
            { name: 'Queen`s Cola (1.5l)', category: DrinkCategory.SOFT_DRINKS, interval: 1 },
            { name: 'Orangensaft', category: DrinkCategory.SOFT_DRINKS, interval: 1 },
            { name: 'Ananassaft', category: DrinkCategory.SOFT_DRINKS, interval: 1 },
            { name: 'Bitter Lemon (1.0l)', category: DrinkCategory.SOFT_DRINKS, interval: 1 },
            { name: 'FS Original (0.33l)', category: DrinkCategory.BEER_WINE, interval: 1 },
            { name: 'EVE Grapefruit Cosmopolitan', category: DrinkCategory.BEER_WINE, interval: 1 },
            { name: 'Braufrisch (0,33l)', category: DrinkCategory.BEER_WINE, interval: 1 },
            { name: 'Somersby', category: DrinkCategory.BEER_WINE, interval: 1 },
            { name: 'Trojka Vodka White', category: DrinkCategory.SPIRITS, interval: 1 },
            { name: 'Trojka Vodka Red', category: DrinkCategory.SPIRITS, interval: 1 },
            { name: 'Trojka Vodka Green', category: DrinkCategory.SPIRITS, interval: 1 },
            { name: 'Bacardi Superior', category: DrinkCategory.SPIRITS, interval: 1 },
            { name: 'Bündner Haselnuss', category: DrinkCategory.SPIRITS, interval: 1 },
            { name: 'Trojka Snow Freak', category: DrinkCategory.SPIRITS, interval: 1 },
            { name: 'Smirnoff Ice', category: DrinkCategory.BEER_WINE, interval: 1 },
            { name: 'Passoa', category: DrinkCategory.SPIRITS, interval: 1 },
            { name: 'Malibu', category: DrinkCategory.SPIRITS, interval: 1 },
            { name: 'Trojka Flamingo ', category: DrinkCategory.SPIRITS, interval: 1 },
            { name: 'Eiswürfel (Kübel)', category: DrinkCategory.MATERIAL, interval: 1 },
            { name: 'Longdrinkbecher', category: DrinkCategory.MATERIAL, interval: 2 },
            { name: 'Shotbecher', category: DrinkCategory.MATERIAL, interval: 2 },
            { name: 'Röhrli kurz', category: DrinkCategory.MATERIAL, interval: 2 }
        ]
    },
    {
        id: 4, name: 'Shot Bar', drinks: [
            { name: 'Willi Sauer', category: DrinkCategory.SPIRITS, interval: 1 },
            { name: 'Jägermeister (0,7l)', category: DrinkCategory.SPIRITS, interval: 1 },
            { name: 'Feigling Coco Biscuit', category: DrinkCategory.SPIRITS, interval: 1 },
            { name: 'Trojka Snow Freak', category: DrinkCategory.SPIRITS, interval: 1 },
            { name: 'Bündner Haselnuss', category: DrinkCategory.SPIRITS, interval: 1 },
            { name: 'Berliner Luft', category: DrinkCategory.SPIRITS, interval: 1 },
            { name: 'Shotbecher', category: DrinkCategory.MATERIAL, interval: 2 }
        ]
    },
    {
        id: 5, name: 'Golfbar', drinks: [
            { name: 'Mineral (0.5l)', category: DrinkCategory.SOFT_DRINKS, interval: 1 },
            { name: 'Coca Cola ( 0.5l)', category: DrinkCategory.SOFT_DRINKS, interval: 1 },
            { name: 'Ice Tea Lemon (0.5l)', category: DrinkCategory.SOFT_DRINKS, interval: 1 },
            { name: 'Citro (1.5l)', category: DrinkCategory.SOFT_DRINKS, interval: 1 },
            { name: 'Trojka Energy (0.25l)', category: DrinkCategory.SOFT_DRINKS, interval: 1 },
            { name: 'Queen`s Cola (1.5l)', category: DrinkCategory.SOFT_DRINKS, interval: 1 },
            { name: 'Bitter Lemon (1.0l)', category: DrinkCategory.SOFT_DRINKS, interval: 1 },
            { name: 'Orangensaft', category: DrinkCategory.SOFT_DRINKS, interval: 1 },
            { name: 'FS Original (0.33l)', category: DrinkCategory.BEER_WINE, interval: 1 },
            { name: 'EVE Grapefruit Cosmopolitan', category: DrinkCategory.BEER_WINE, interval: 1 },
            { name: 'Braufrisch (0,33l)', category: DrinkCategory.BEER_WINE, interval: 1 },
            { name: 'Somersby', category: DrinkCategory.BEER_WINE, interval: 1 },
            { name: 'Trojka Vodka White', category: DrinkCategory.SPIRITS, interval: 1 },
            { name: 'Trojka Vodka Red', category: DrinkCategory.SPIRITS, interval: 1 },
            { name: 'Trojka Vodka Green', category: DrinkCategory.SPIRITS, interval: 1 },
            { name: 'Bacardi Superior', category: DrinkCategory.SPIRITS, interval: 1 },
            { name: 'Shot Sex on the Beach', category: DrinkCategory.SPIRITS, interval: 1 },
            { name: 'Ballantine`s Whisky', category: DrinkCategory.SPIRITS, interval: 1 },
            { name: 'Baileys', category: DrinkCategory.SPIRITS, interval: 1 },
            { name: 'Berliner Luft', category: DrinkCategory.SPIRITS, interval: 1 },
            { name: 'Smirnoff Ice', category: DrinkCategory.BEER_WINE, interval: 1 },
            { name: 'Eiswürfel (Kübel)', category: DrinkCategory.MATERIAL, interval: 1 },
            { name: 'Longdrinkbecher', category: DrinkCategory.MATERIAL, interval: 2 },
            { name: 'Shotbecher', category: DrinkCategory.MATERIAL, interval: 2 },
            { name: 'Röhrli kurz', category: DrinkCategory.MATERIAL, interval: 2 },
        ]
    },
    {
        id: 6, name: 'Container Bar', drinks: [
            { name: 'Mineral (0.5l)', category: DrinkCategory.SOFT_DRINKS, interval: 1 },
            { name: 'Coca Cola ( 0.5l)', category: DrinkCategory.SOFT_DRINKS, interval: 1 },
            { name: 'Ice Tea Lemon (0.5l)', category: DrinkCategory.SOFT_DRINKS, interval: 1 },
            { name: 'Citro (1.5l)', category: DrinkCategory.SOFT_DRINKS, interval: 1 },
            { name: 'Trojka Energy (0.25l)', category: DrinkCategory.SOFT_DRINKS, interval: 1 },
            { name: 'FS Original (Fass)', category: DrinkCategory.BEER_WINE, interval: 1 },
            { name: 'FS Alkoholfrei (0.33l)', category: DrinkCategory.BEER_WINE, interval: 1 },
            { name: 'Somersby (0.33l)', category: DrinkCategory.BEER_WINE, interval: 1 },
            { name: 'Braufrisch (Fass)', category: DrinkCategory.BEER_WINE, interval: 1 },
            { name: 'Eve Grapefruit Cosmopolitan', category: DrinkCategory.BEER_WINE, interval: 1 },
            { name: 'Jägermeister (0,7l)', category: DrinkCategory.SPIRITS, interval: 1 },
            { name: 'Berliner Luft', category: DrinkCategory.SPIRITS, interval: 1 },
            { name: 'Smirnoff Ice', category: DrinkCategory.BEER_WINE, interval: 1 },
            { name: 'Bierbecher ', category: DrinkCategory.MATERIAL, interval: 2 },
            { name: 'Shotbecher', category: DrinkCategory.MATERIAL, interval: 2 }
        ]
    },
    {
        id: 7, name: 'Foodcorner', drinks: [
            { name: 'Plastikteller', category: DrinkCategory.MATERIAL, interval: 2 },
            { name: 'Kaffeelöffeli', category: DrinkCategory.MATERIAL, interval: 2 },
            { name: 'Kaffeebecher', category: DrinkCategory.MATERIAL, interval: 2 },
            { name: 'Zucker', category: DrinkCategory.MATERIAL, interval: 2 },
            { name: 'Kaffeekapseln', category: DrinkCategory.MATERIAL, interval: 2 },
            { name: 'Rähmli', category: DrinkCategory.MATERIAL, interval: 2 },
        ]
    }
];
